### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ExE-Boss** [hax/etab#3]
This repository is currently [unlicensed](https://choosealicense.com/no-license/) which makes it so that nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has [other contributors](https://github.com/hax/etab/pull/2) (each a copyright holder), “nobody” starts including you.

### What can you do?
The best solution is to just [choose a license](https://choosealicense.com/).

**Comment by hax** [comment]
This project is just using the ISC license as the package.json ( https://github.com/hax/etab/blob/master/package.json#L23 )

**Comment by ExE-Boss** [comment]
Then add the ISC license to a file called `LICENSE` in the root of the repo. (So that GitHub can show the license in the top bar ([like in this repo for example](https://github.com/ExE-Boss/exe-boss.github.io)) and so that the license is easy to find, [the `LICENSE` file is a GitHub standard after all](https://help.github.com/articles/licensing-a-repository/#determining-the-location-of-your-license))
